### PR TITLE
[WIP] sy5.4/6 compatibility

### PR DESCRIPTION
**Pull request by mihaileu**
In order to go further: 
- upgrade the phpunit to 905
- apply cs fixes
- upgrade php version to 7.4 a

This will help with https://github.com/mmoreram/GearmanBundle/pull/197

### CODE REVIEW

**Comment by mihaileu** [comment]
@daum this will be a major change, I'm entering in refactoring all the code. Hope it will not be an issue to merge it and in increasing the major tag. It will have some breaking changes.

**Comment by daum** [comment]
@mihaileu  awesome, thank you so much for all the much needed maintenance!

**Comment by mihaileu** [comment]
@mmoreram @daum It passed my manual tests and seems it work, at least what I tried till now.
I see this way of going further:
1. create a develop branch for this: 5, or sy5_6 compatibility where we can merge this.
2. Release a 5-dev tag
3. we will do further tests as we migrate a project which is using intensive the gearman bundle. 
4. adding further changes to that branc in order to be easy to review them
5. once we consider that is stable to migrate in master and delete old branch.

What do you say ?

**Comment by daum** [comment]
I think that make sense to me too.  I unfortunately right now don't have much time to help contribute to this update due to a number of other deadlines i'm hitting.  @mmoreram  think we can get Mihaileu added as a maintainer?

**Comment by mmoreram** [comment]
@daum I added @mihaileu as a collaborator :)
Good work!

**Pull request merged**
