### PR TITLE
Enable for graceful restarts on systems with pcntl_signal enabled.

### PR DESCRIPTION
**Pull request by daum**
If the process recieves a SIGTERM or SIGHUP it will restart after current job is done or timeout is received.  This should solve issue #134 .  

If you have a worker which may not receive any work for a while it is smart to set the timeout for that worker.  If you do not, the worker will not restart until AFTER it receives the next job.

### CODE REVIEW

**Comment by mmoreram** [comment]
Great job!

Two things here:
* @gcavana @jamesrgrinter @chyzas This PR has been done under a branch inside the GearmanBundle repository for providing an easy interface to be tested in your projects. Can you provide some testing here?
* @daum Can you please pass the php-cs-fixer here?

Ping me for anything :)

**Comment by daum** [comment]
@mmoreram php-cs-fixer touches pretty much every file in the bundle (adds .'s to comments, etc.) not sure we should bundle that in with this update.

**Comment by mmoreram** [comment]
Sure :)

**Comment by mmoreram** [comment]
btw, can you squash both commits in one?

**Comment by daum** [comment]
Yep - all set.  Just did that.

**Comment by daum** [comment]
@gcavana @jamesrgrinter @chyzas  were any of you able to test this?  I have tested it myself and it looks like it is working fine just wanted to have some outside validation on top.

**Comment by jamesrgrinter** [comment]
I haven't yet, but it's on my list of things to do!

**Comment by mmoreram** [comment]
@jamesrgrinter nice!
Ping us when is done :)

cc/ @daum

**Comment by daum** [comment]
@jamesrgrinter any chance you had this tested?  Just wanted to see if we want to merge this into the master.  I've been using the branch in production since it was created and have not had any problems.

**Comment by jamesrgrinter** [comment]
I've started on a bit of integration testing, so far so good. I need to try some more disruptive/harder ways to initiate the restarts, just to make sure it isn't losing any operations.

(I can confirm the "If you do not, the worker will not restart until AFTER it receives the next job" behaviour, though. I need to look at the timeouts, for my own situation!)

**Comment by daum** [comment]
@jamesrgrinter  any further tests with this?  Would like to get this merged in to master soon.

**Comment by mmoreram** [comment]
@daum Seen that this bundle is very used by a lot of people, I would consider making a small effort on covering it with a bigger test battery. When I started this bundle, and when I refactor it, I was not very aware of the importance of tests when developing :/

**Comment by daum** [comment]
@mmoreram not sure how we should test this one as you'd need more of a full blown setup going?

**Comment by daum** [comment]
Just wanted to see if anyone had any ideas for additional tests on this or if it should be merged.

**Pull request merged**
