### PR TITLE
#169

### PR DESCRIPTION
**Pull request by er1z**
See issue #169.

This commit fixes weird issue. To clarify what was wrong:
- `addFunction` needs `$context` param to be a _reference_, not value. Someone (I have not checked who) ignored docs and passed the second one,
- when I extracted array to a local variable, segfault also occurred - probably due to the incorrect garbage collection,
- configuration (and object with worker) left in `GearmanExecute::$workersBucket` survives GC and works ok.

### CODE REVIEW

**Comment by daum** [comment]
Can you please provide a test case for where this fails just so we can verify/see what is occurring.

**Comment by er1z** [comment]
Clone:
https://github.com/er1z/gearman-bundle-test

Enqueue: ``php bin/console app:test``
Worker: ``php bin/console gear:jo:e  AppBundleWorkerGeneratorWorker~process -n``

What causes:

```
@worker\servers :

    #localhost - 127.0.0.1:4730

@Worker\description :

    No description is defined

@job\methodName : process
@job\callableName : AppBundleWorkerGeneratorWorker~process
@job\supervisord : /usr/bin/php /workspace/appstore/gearman-test/app/console gearman:job:execute AppBundleWorkerGeneratorWorker~process --no-interaction
@job\iterations : 150
@job\defaultMethod : doNormal

@job\servers :

    localhost - 127.0.0.1:4730

@job\description :

    #No description is defined

[2016-09-20 12:28:58] loaded. Ctrl+C to break
zsh: segmentation fault (core dumped)  php bin/console gear:jo:e AppBundleWorkerGeneratorWorker~process -n
```

On:

```
 % php -v
PHP 7.0.10-2+deb.sury.org~trusty+1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.10-2+deb.sury.org~trusty+1, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.4.1, Copyright (c) 2002-2016, by Derick Rethans
```

**Comment by er1z** [comment]
Somehow this build segfaulted on running phpunit. Dafq?

**Comment by daum** [comment]
Yep just tried it locally to to see, and getting the segfault.  I don't have time to try to dive into this right now but will try to look in a couple of weeks.

**Comment by sudevva** [comment]
Tested a205e9d:Service/GearmanExecute.php.
No segmentation fault.
Please take care of it.

**Comment by mikaelkael** [comment]
SGTM :+1: !

**Comment by malarzm** [comment]
Just want to confirm that with this PR applied I got rid of 

```
[InvalidArgumentException]                                               
$context shall be an array with job_object_instance and job_method key.
```

that was thrown on every 2nd job when using PHP 7.1.1 and everything is working as expected, would be great to see this merged :+1:

**Comment by daum** [comment]
@malarzm We need to get the CI running properly.  I haven't had a chance to look into this.  If you can look into and get it passing the CI we can work on getting this merged in.

**Comment by malarzm** [comment]
@daum could you re-run travis to see if the segfault is still there?

**Comment by daum** [comment]
Just kicked it off.

**Comment by malarzm** [comment]
All right, I see the segfault is still there. I'll give it a spin locally on PHP 7.1 to see if it's there too, if not I'll try to have PHP 5.6 running

**Comment by daum** [comment]
Thanks we should probably add PHP 7.0 and 7.1 to the CI too since we support it.  If you have a few to add those into the config so they are running too it'd be appreciated!

**Comment by mikaelkael** [comment]
I integrated it in my fork: https://github.com/mikaelkael/GearmanBundle ; the build is OK => https://travis-ci.org/mikaelkael/GearmanBundle

**Comment by malarzm** [comment]
I think I've found the reason of segfault, I'll try to have it up and running on PHP 7.1 and then submit a PR

**Comment by daum** [comment]
Awesome thanks @malarzm

**Comment by mikaelkael** [comment]
Be careful of the gearman extension version:
 - PHP 5.x: http://pecl.php.net/get/gearman/1.1.2
 - PHP 7.x: https://github.com/wcgallego/pecl-gearman/archive/gearman-2.0.1.tar.gz

**Comment by malarzm** [comment]
@mikaelkael will you submit update to travis configuration to run on PHP 7 as you have it ready in your fork?

**Comment by daum** [comment]
This was merged in via https://github.com/mmoreram/GearmanBundle/pull/175

**Pull request closed without merging**
