### PR TITLE
Fix segmentation fault

### PR DESCRIPTION
**Pull request by malarzm**
As I already had changes done by @er1z ported to fork of ours I've allowed myself to build this PR on it, if I should include original commits and only add mine that is fixing tests please let me know.

### CODE REVIEW

**Comment by daum** [comment]
Thanks looking at this now, thanks for getting the tests to pass.   Are you waiting on @mikaelkael to add to a branch to make a different PR for the travis config?  Or do you want to just update your branch with the 7.0 and 7.1 configurations?  Otherwise in the meantime will locally just test a few things to make sure these changes don't cause any other issues.

**Comment by daum** [comment]
Everything looks pretty good to me.  @er1z thanks for pointing out the addFunction being improperly given a value rather than reference and making the updates there.  @malarzm  thanks for updating the test to not segfault.

I think once we get 7.0+7.1 added to the travis configuration on this PR, assuming it passes, I'll merge it in.

**Comment by malarzm** [comment]
> Are you waiting on @mikaelkael to add to a branch to make a different PR for the travis config? Or do you want to just update your branch with the 7.0 and 7.1 configurations?

I can add the the configuration to travis tomorrow morning or if Mickael beats me to it with PR I'll just rebase mine atop of `master` once it's merged :)

**Comment by malarzm** [comment]
@daum not exactly my morning but I'm sure it's morning somewhere ;) Anyways, the travis is updated to use correct extension as per configuration in @mikaelkael's fork and the build is green \o/

**Comment by daum** [comment]
Thanks a ton @malarzm  for all the work on merging the different PRs, getting this fixed and update the travis integration.  I've merged this and created a release v4.0.2

**Comment by malarzm** [comment]
Glad I could help!

**Pull request merged**
