### PR TITLE
New GEARMAN_WORK_STARTING event on new job

### PR DESCRIPTION
**Pull request by dav-m85**
In order to implement a clean worker shutdown (incoming pull request), I need a new event to be dispatched when a worker starts to process a new job. I added testing for the existing GEARMAN_WORK_EXECUTED event, and for the new one.

I opened also a [pull request](https://github.com/lafourchette/GearmanBundle/pull/1) against our company fork.

### CODE REVIEW

**Comment by dav-m85** [comment]
If you're interested, I also implemented a backport for [v2.3.3 here](https://github.com/lafourchette/GearmanBundle/pull/2)

Sadly, we're still using symfony 2.1 on some projects.

**Comment by mmoreram** [comment]
@dav-m85 Awesome!

Have you checked this feature is not BCBreak?

**Comment by mmoreram** [comment]
BTW, If you're using SF2.1 you can upgrade to SF2.6 right? I mean, there is no BC Break, so you shouldnt have any problem :S

**Comment by dav-m85** [comment]
It is not, I simply proxy the add_function call to capture new jobs and send the starting event.

The projet on which I intend to use the feature is dead locked on sf2.1, and I cannot upgrade past 2.3.3 because of the DoctrineCache dependency (which requires sf/framework 2.4). Backporting was quite easy so that's the solution I chose.

**Comment by dav-m85** [comment]
I added the ability to workers to end themselves on USR1 signal, you can have a look at it on https://github.com/lafourchette/GearmanBundle/pull/3

No BC-break so far. Would you like me to forward-porting this feature ?

**Comment by mmoreram** [comment]
Great. Would be nice to document these new features before merging.

Could you please add it? Or anyone?

**Comment by dav-m85** [comment]
Yes sure, I'll work on it.

**Comment by mmoreram** [comment]
Ping @dav-m85 Any documentation here?

**Comment by dav-m85** [comment]
@mmoreram Documentation added ! Not sure it is enough though, please give directions if not :)

**Comment by mmoreram** [comment]
@dav-m85 Awesome. I will merge this PR, and please, I will need some feedback :)

**Pull request merged**
